export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL"
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET"

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST"
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL"
export const GET_REVIEW_RESET = "GET_REVIEW_RESET"



export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST"
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS"
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL"
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET"



export const GET_SINGLE_REVIEW_REQUEST = "GET_SINGLE_REVIEW_REQUEST"
export const GET_SINGLE_REVIEW_SUCCESS = "GET_SINGLE_REVIEW_SUCCESS"
export const GET_SINGLE_REVIEW_FAIL = "GET_SINGLE_REVIEW_FAIL"
export const GET_SINGLE_REVIEW_RESET = "CREATE_REVIEW_RESET"


export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"